### ISSUE TITLE
Video Recorder - Crashing

### ISSUE THREAD

**Issue by Casesos** [Skretzo/runelite-plugins#12]
Upon starting the plugin in resizeable mode with stretched mode this error happens after crashing client.

```java
2022-08-05 13:37:06 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.desktop/java.awt.image.BufferedImage.<init>(Unknown Source)
	at net.runelite.client.plugins.gpu.GpuPlugin.screenshot(GpuPlugin.java:1376)
	at net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$1750/0x0000000100b06840.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1280)
	at as.z(as.java:56958)
	at as.run(as.java:340)
	at java.base/java.lang.Thread.run(Unknown Source)
2022-08-05 13:37:09 [pool-3-thread-1] WARN  c.videorecorder.VideoRecorderPlugin - Error while writing video frame
java.io.IOException: closed
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.checkClosed(Unknown Source)
	at java.desktop/javax.imageio.stream.ImageInputStreamImpl.getStreamPosition(Unknown Source)
	at com.videorecorder.video.avi.AVIWriter.getRelativeStreamPosition(AVIWriter.java:1674)
	at com.videorecorder.video.avi.AVIWriter$Chunk.<init>(AVIWriter.java:1426)
	at com.videorecorder.video.avi.AVIWriter$CompositeChunk.<init>(AVIWriter.java:1462)
	at com.videorecorder.video.avi.AVIWriter.writeProlog(AVIWriter.java:628)
	at com.videorecorder.video.avi.AVIWriter.ensureStarted(AVIWriter.java:471)
	at com.videorecorder.video.avi.AVIWriter.writeSample(AVIWriter.java:535)
	at com.videorecorder.video.avi.AVIWriter.write(AVIWriter.java:308)
	at com.videorecorder.VideoRecorderPlugin.screenshot(VideoRecorderPlugin.java:300)
	at com.videorecorder.VideoRecorderPlugin.lambda$toggleVideo$2(VideoRecorderPlugin.java:227)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Skretzo** [comment]
> Upon starting the plugin

Does this really happen when you start the plugin or when you start a recording?

> in resizeable mode with stretched mode

Do you play with a very big resolution? Does it not happen with stretched mode turned off?

**Comment by rodhfr** [comment]
happens to me also
```bash
java.lang.OutOfMemoryError: Java heap space
	at java.desktop/java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.desktop/java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:324)
	at net.runelite.client.plugins.gpu.GpuPlugin.screenshot(GpuPlugin.java:1443)
	at net.runelite.client.plugins.gpu.GpuPlugin$$Lambda$2172/0x0000000100c94040.get(Unknown Source)
	at net.runelite.client.ui.DrawManager.processDrawComplete(DrawManager.java:84)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1350)
	at bm.ac(bm.java:18558)
	at bm.run(bm.java:382)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
On Pop-os! 22.04 which is Ubuntu using x.org .
Using mesa drivers on RX 580 and vanilla GPU plugin. Tested with stretched mode turned "on" and "off" and the result were the same. It  does crashes when I unfocus from the client, but not exactly instantaneously, more like, if I didn't unfocus it apparently does not crash.
