### ISSUE TITLE
Line markers occasionally crashes on startup

### ISSUE THREAD

**Issue by rdutta** [Skretzo/runelite-plugins#59]
```
2024-11-01 19:23:22 MDT [AWT-EventQueue-0] ERROR n.r.client.plugins.PluginManager - Unable to start plugin LineMarkerPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException
        at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:460)
        at net.runelite.client.plugins.PluginManager.lambda$startPlugins$2(PluginManager.java:241)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NullPointerException: null
        at net.runelite.api.coords.WorldPoint.toLocalInstance(WorldPoint.java:333)
        at net.runelite.api.coords.WorldPoint.toLocalInstance(WorldPoint.java:324)
        at com.linemarkers.Line.instances(Line.java:33)
        at com.linemarkers.LineGroup.instances(LineGroup.java:38)
        at com.linemarkers.LineMarkerPlugin.mirrorMarkers(LineMarkerPlugin.java:375)
        at com.linemarkers.LineMarkerPlugin.loadMarkers(LineMarkerPlugin.java:350)
        at com.linemarkers.LineMarkerPlugin.startUp(LineMarkerPlugin.java:201)
        at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:438)
        ... 14 common frames omitted
```

This is during the start up of the runelite client; i think WorldView might be null sometimes?

**Comment by Skretzo** [comment]
I have added a fix that hopefully solves this problem. It will be live in the client after review, which typically takes about 1 week (edit: it has been released).
